---
- hosts: heads-tails

  become: yes

  roles:
    - { role: setup_ssh }

  tasks:

  - name: Disable Bluetooth
    blockinfile:
      create: yes
      path: /boot/config.txt
      insertafter: '^[all]'
      state: present
      block: |
        dtoverlay=pi3-disable-bt

  - name: Disable hciuart systemd service
    systemd:
      name: hciuart
      enabled: no
  
  - name: Disable bluetooth systemd service
    systemd:
      name: bluetooth
      enabled: no

  - name: Ensure the locale exists
    locale_gen:
      name: en_US.UTF-8
      state: present
      
  # - name: set as default locale
  #   command: localectl set-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

  - name: Change hostname to inventory_hostname in ./inventory/all
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Change raspberrypi to inventory_hostname in /etc/hosts
    lineinfile:
      path: /etc/hosts
      regex: '^127\.0\.1\.1'
      line: "127.0.1.1  {{ inventory_hostname }}"

  - name: Download signing keys
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: "{{ item }}"
      state: present
    with_items:
      - 7638D0442B90D010
      - 8B48AD6246925553
      - 04EE7237B7D453EC

# Update Installed Packages

  - name: Update installed packages
    apt:
      update_cache: yes
      upgrade: full
      autoremove: yes
      autoclean: yes
      force: yes

# Install Wireguard for PI (ref: https://github.com/adrianmihalko/raspberrypiwireguard)

  - name: Install "raspberrypi-kernel-headers"
    apt:
      name: raspberrypi-kernel-headers
      update_cache: yes

  - name: Upload unstable.list to /etc/apt/sources.list.d/
    copy:
      src: unstable.list
      dest: /etc/apt/sources.list.d/

  - name: Install dirmngr
    apt:
      name: dirmngr
      update_cache: yes

  - name: upload limit-unstable to /etc/apt/preferences.d/
    copy:
      src: limit-unstable
      dest: /etc/apt/preferences.d/

  - name: Install WireGuard
    apt:
      name: wireguard
      update_cache: yes

# Finish Installing Additional Packages

  - name: Install required packages
    apt:
      update_cache: yes
      name: [ git, python3-rpi.gpio, tmux, python-pip ]

# Setup New User with Sudo and NOPASSWD 
# and because I always forget... here's how to generate a nicely hashed password
# https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module

  - name: Reboot!
    reboot:
      msg: "Hold on to your butts!"

  - name: Remove the user 'pi'
    user:
      name: pi
      state: absent
      remove: yes






